# Generated by Django 3.2 on 2023-11-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='like_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='write_comment_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_movie_comment', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='write_comment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='write_comment', to='accounts.user'),
            preserve_default=False,
        ),
    ]
